### PR TITLE
Added Navigation Bar to the UI

### PR DESCRIPTION
**Pull request by AfandiM**
Added Navigation Bar to the UI, it still needs some tweaks, but they will be taken care of as soon as other pages are done (for navigation)

Refers to #25

### CODE REVIEW

**Review by kalsij — APPROVED** [review]
Looks Good!

**Comment by julietrinh1** [comment]
Is it just me, or do I not see the navigation bar?

**Comment by AfandiM** [comment]
> Is it just me, or do I not see the navigation bar?

That's odd. it should be visible. Maybe make sure that the <Navbar /> element is in App.js

**Comment by julietrinh1** [comment]
Really nicely done!

**Review by julietrinh1 — COMMENTED** [review]
Everything looks good and works for me, nice work

**Pull request merged**
